import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainLayout from '~/components/Layout/MainLayout';
import { ThemeProvider } from '~/components/ThemeProvider'
import '~/styles/globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body suppressHydrationWarning={true}>
        <ThemeProvider>
          <MainLayout>
            {children}
          </MainLayout>
        </ThemeProvider>
      </body>
    </html>
  )
}
